# 机器人基础配置
settings:
  trigger: "巴拉"          # 机器人名称
  duration: "24h"        # 每一轮监听的时长
  loop_interval: 10        # 轮询间隔（秒）
  max_workers: 3          # 最大并发线程数

# API 接口配置
api:
  daily_news:
    url: "60s.viki.moe"
    path: "/v2/60s?encoding=image"
    method: "GET"
  crazy_kfc:
    url: "60s.viki.moe"
    path: "/v2/kfc"
    method: "GET"
  slacker_daily:
    url: "60s.viki.moe"
    path: "/v2/moyu?encoding=text"
    method: "GET"
  dad_joke:
    url: "60s.viki.moe"
    path: "/v2/dad-joke?encoding=text"
    method: "GET"

# 监听的好友列表
friends:
  - "Felix"