# 机器人基础配置
settings:
  duration: "24h"        # 每一轮监听的时长
  loop_interval: 5        # 轮询间隔（秒）
  max_workers: 3          # 最大并发线程数

# API 接口配置
api:
  news_60s:
    url: "60s.viki.moe"
    path: "/v2/60s?encoding=image"
    method: "GET"

# 监听的好友列表
friends:
  - "Felix"